// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gygqttrymfjavfpkyguh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5Z3F0dHJ5bWZqYXZmcGt5Z3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTc3ODAsImV4cCI6MjA3MTk3Mzc4MH0.ZRu4oUAFM49Eu6NsbKmjfyH2IXxj-JwpfUQHeAq-dJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});